version: '3.8'

services:
  wedding-backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/usr/src/app/database
    environment:
      - NODE_ENV=production
    restart: unless-stopped